### ISSUE TITLE
Add pictures/logo to blog

### ISSUE THREAD

**Issue by aditya2592** [quadrotor-IITKgp/ark-blog#2]

**Comment by sam17** [comment]
Suggestions on where?

**Comment by aditya2592** [comment]
Logo above May the thrust be with you ? Pics need to think
Also you can replace twitter/facebook with logos or put the like box itself

**Comment by sam17** [comment]
I wanted to keep it minimalistic so I think we should not put pictures on home except logo.
Yea I will change the twitter/facebook.

**Comment by kumarkrishna** [comment]
The logo with `May the thrust be with you` in subscript sounds good 👍
